version: '3'

services:
  app:
    build: ./app
    container_name: app
    ports:
      - "5000:5000"  # Expose port 5000 from the container to port 5000 on the host
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=safedb
    depends_on:
      - mysql  # Ensure MySQL container is ready before the app starts

  client_1:
    build: ./client
    container_name: client1
    environment:
      - SERVER_URL=http://app:5000  # Point client to the 'app' service
    depends_on:
      - app  # Ensure the app container is ready before the client starts

  client_2:
    build: ./client
    container_name: client2
    environment:
      - SERVER_URL=http://app:5000  # Point client to the 'app' service
    depends_on:
      - app  # Ensure the app container is ready before the client starts

  mysql:
    build: ./mysql
    container_name: mysql
    ports:
      - "3306:3306"  # Expose MySQL on the default MySQL port
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=safedb
    restart: always
